return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	opts = {
		ensure_installed = {
			"c",
			"lua",
			"vim",
			"vimdoc",
			"heex",
			"javascript",
			"html",
			"go",
			"python",
			"json",
			"css",
			"typescript",
			"tsx",
			"cpp",
			"bash",
			"dockerfile",
			"graphql",
			"yaml",
		},
		auto_install = true,
		-- sync_install = false,
		highlight = { enable = true },
		indent = { enable = true },
	},
}
